### ISSUE TITLE
Basic questions about C/C++ minpack

### ISSUE THREAD

**Issue by lukkio88** [devernay/cminpack#16]
Hi,

I'm considering using your package for a problem I have.
1. Can your tool be used in visual studio 2015, windows 10?
2. I can see some CUDA source files, are the minimization algorithms implemented in CUDA as well? or they're just generic examples?
3. Can your tool fit a functions f : R^m -> R^n? or is it restricted only to scalar functions?
4. If 3 is yes, is there a bound on the number of parameters to be fit? I have to fit functions that have 192^2 parameters.

Thank you

**Comment by devernay** [comment]
1- probably, since it is standard C. You can even generate a VS solution using CMake

2- these are CUDA ports of the minpack functions, in case you need these. It may be useful if you have to run multiple times the same problem with different parameters

3- yes, it does a least squares fit

4- no bound, except for your memory and processing time!

if you don't have enough memory to compute the  jacobian, you can use the lmstr subroutine, which asks for lines of the jacobian (see the example)
